services:
  nats:
    image: nats:2.10.22-alpine3.20
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: pipeline
    env_file:
      - .env
